#!/bin/sh

#author: Alejandro Erickson
if [ -d inrflow.$$.d ]; then
    echo "Directory inrflow.$$.d exists.  Try again."
    exit 1;
fi

cat <<EOF

This script will clean your build directory and compile INRFlow.  If
you supply a file with a list of arguments to inrflow, the arguments
in the file will be tested, and otherwise those generated by
./gen_test_args.sh.

inrflow output in inrflow.$$.d/n.out.

Do you wish to continue? RET / CTRL-c|n|N|q|Q

EOF

read response
if [ "$response" = "n" ] || [ "$response" = "N" ] || [ "$response" = "q" ] || [ "$response" = "Q" ] 
then
    exit
fi
(cd ../ && make clean)

echo "Debug flags on? RET / n|N"
read response
if [ "$response" = "n" ] || [ "$response" = "N" ]
then
    (cd ../ && make all)
else    
    (cd ../ && make all CFLAGS="-DDEBUG -g")
fi

mkdir inrflow.$$.d && cp .././build/bin/inrflow inrflow.$$.d/ && cp ../pretty_data.tex inrflow.$$.d/ && cp ../stats_only.tex inrflow.$$.d/ && cp inrflow.conf inrflow.$$.d/ && cd inrflow.$$.d

if [ $? -ne 0 ]; then
    echo "failed to setup working directory"
    exit 1
fi

cat<<EOF

Working directory:
EOF

pwd

cat<<EOF

EOF

if [ $# -ge 1 ]
then
    TEST_ARGS="cat ../$1"
else
    TEST_ARGS=".././gen_test_args.sh"
fi

${TEST_ARGS} | \
		while read A; do
				./inrflow ${A}
				if [ "$?" != "0" ]
				then
						echo "INRFlow bad exit code for parameters:"
						echo "${A}"
						exit 1
				fi
		done

